name: Weekly accessibility audit

on:
  schedule:
    - cron:  '0 6 * * 1'   # 06:00 every Monday UTC :contentReference[oaicite:4]{index=4}
  workflow_dispatch:       # manual run button

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      REPORT_DATE: ${{ github.run_started_at }}    # 2025-05-29T07:00:00Z
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm i

      # ───────── Lighthouse CI (exec-summary for execs) ─────────
#      - name: Lighthouse CI
#        run: |
#          npx lhci autorun \
#            --max-wait-for-load=60000 \
#            --upload.target=filesystem \
#            --upload.outputDir=public/lhci/$REPORT_DATE \
#            --collect.url=$(tr '\n' ' ' < urls.txt) \
#            --chrome-flags="--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu --disable-extensions --disable-background-timer-throttling --disable-renderer-backgrounding"

      # ───────── Pa11y-CI (full WCAG backlog) ─────────
      - name: Pa11y CI
        run: |
          mkdir -p public/pa11y/$REPORT_DATE
          npx pa11y-ci --config .pa11yci.js
        continue-on-error: true


  # ───────── Publish to GitHub Pages ─────────
  deploy:
    permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
      contents: write
      pages: write
      id-token: write
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository for Deployment
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Deploy Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # This directory contains all your files