name: Weekly accessibility audit

on:
  schedule:
    - cron:  '0 6 * * 1'   # 06:00 every Monday UTC :contentReference[oaicite:4]{index=4}
  workflow_dispatch:       # manual run button

jobs:
  audit:
    permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      REPORT_DATE: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      # ───────── Lighthouse CI (exec-summary for execs) ─────────
#      - name: Lighthouse CI
#        env:
#          REPORT_DATE: ${{ env.REPORT_DATE }}
#        run: |
#          npx lhci autorun \
#            --max-wait-for-load=60000 \
#            --upload.target=filesystem \
#            --upload.outputDir=public/lhci/$REPORT_DATE \
#            --collect.url=$(tr '\n' ' ' < urls.txt) \
#            --chrome-flags="--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu --disable-extensions --disable-background-timer-throttling --disable-renderer-backgrounding"

      # ───────── Pa11y-CI (full WCAG backlog) ─────────
      - name: Pa11y CI
        env:
          REPORT_DATE: ${{ env.REPORT_DATE }}
        run: |
          mkdir -p ./public/pa11y/$REPORT_DATE
          npx pa11y-ci --config .pa11yci.js
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true      # preserves historical folders
          commit_message: "chore(reports): deploy ${{ github.run_id }} on ${{ env.REPORT_DATE }}"